---
- hosts: all

  become: true
  tasks:
    - name: deploy zabbix agent
      community.zabbix.zabbix_agent:
        agent_param_server: "192.168.4.22"
        agent_param_serveractive: "192.168.4.22"
